### ISSUE TITLE
Better compatibility with XO Prettier

### ISSUE THREAD

**Issue by vabatta** [xojs/eslint-config-xo-typescript#10]
By enabling XO prettier and using this plugin, you get duplicated errors with rules `@typescript-eslint/indent` and `@typescript-eslint/semi`. There should be auto compatibility as they are both integrated within `XO`.

**Comment by sindresorhus** [comment]
Not much we can do until https://github.com/xojs/xo/issues/373 is done, as shareable rules cannot really check if whether other rules exists.

**Comment by Tapppi** [comment]
@sindresorhus the linked issue is now closed, is there any news on this?

**Comment by sindresorhus** [comment]
Yes. It's now possible. Not something I plan to work on though.
