### ISSUE TITLE
TypeScript-ESLint v2 was just released

### ISSUE THREAD

**Issue by jedmao** [xojs/eslint-config-xo-typescript#13]
So far, the only issue I've run into with v2 is the [`array-type`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md) rule, which needs to be changed to an object instead of a string. Might be more discrepancies though.

```json
    "@typescript-eslint/array-type": [
      "error",
      {
        "default": "array-simple"
      }
    ],
```

https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0

**Comment by sindresorhus** [comment]
I prefer to wait a bit. Most releases from that project is buggy at first.
