### ISSUE TITLE
[no-unnecessary-condition] should enable ignoreRhs

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/eslint-config-xo-typescript#17]
The rule option `ignoreRhs` should be enabled. This is an error I had which is gone with the option enabled:

```ts
interface Foo {
	bar?: string[];
}

const obj: Foo = {};
const alwaysArray = obj.bar || [];
```

With message `6:32  Unnecessary conditional, value is always truthy.` which marks the array on the right side as unnecessary condition as `[]` is always true. Which is exactly what I want in this case.

Documentation: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md

**Comment by yangmingshan** [comment]
I need this too, it's very useful in jsx.
```js
{condition && < SomeComponent />}
```
