### ISSUE TITLE
Example doesn't get things to fire

### ISSUE THREAD

**Issue by emarcotte** [xojs/eslint-config-xo-typescript#2]
Hi,

The example in the README doesn't quite cause xo to fire for me. I find that I actually need to specify the extensions, something like:
```json
{
	"name": "my-awesome-project",
	"xo": {
		"extends": "xo-typescript",
		"extensions": ["ts"]
	}
}
```

Is this expected behavior?

**Comment by sindresorhus** [comment]
Yes, that's currently needed. I forgot to document it.

Hopefully, https://github.com/eslint/eslint/issues/10828 will be fixed at some point.
