### ISSUE TITLE
array-type configuration differs from Visual Studio Code preview

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/eslint-config-xo-typescript#25]
The preview in Visual Studio Code automatically uses `readonly T[]` over `ReadonlyArray<T>`.
When looking on Previews of functions and parameters I get familiar with this style of writing parameters. The current rules want me to write a different style.

I havnt looked into Visual Studio Codes Preview Logic or why they do it that way. I only want to start a discussion about it.

These two following methods are accepting the same parameter but the preview of these is the same. The first one produces this xo error:
`Array type using T[] is forbidden for non-simple types. Use Array<T> instead. @typescript-eslint/array-type`

```ts
export function foo(something: readonly Readonly<Something>[]): number {
  return something.length
}

export function bar(something: ReadonlyArray<Readonly<Something>>): number {
  return something.length
}
```

![Screenshot of Visual Studio Code showing the code example](https://user-images.githubusercontent.com/7953011/79112544-14b5d180-7d7f-11ea-8ab2-52555dbba996.png)

![Screenshot of Visual Studio Code with a more complex parameter](https://user-images.githubusercontent.com/7953011/79112761-9dcd0880-7d7f-11ea-85e7-336a8a2c2b0c.png)

What are other opinions about changing the rule `array-type` towards simple arrays?

**Comment by sindresorhus** [comment]
I agree that the first one is nicer. The point of the rule was to prevent things like `(string | boolean)[]` in favor of `Array<string | boolean>`. Maybe the rule could be made better somehow?

**Comment by EdJoPaTo** [comment]
I tend towards using extra types if unions are more complex. `string | boolean` might still end up in brackets for me but as soon as there are three or one of them isn't a basic type anymore the union will get its own type. That improves readability for me and I am able to use the inner type more easily.

Thinking about that maybe a rule for disallowing non plain unions would be better than a specific array-type based on their content?
For example this would be allowed:
```ts
type A = number | string | boolean
type B = Array<A>
type C = readonly A[]
```
And this would be disallowed as the unions are not at the top level
```ts
type B = Array<number | string | boolean>
type C = readonly (number | string | boolean)[]
```

Maybe this could be configurable to allow union of simple types like this: `Array<string | boolean>` as they are still relatively easy to read.

There is no rule like that currently existing nor an issue suggesting such rule.
For now its just a quick thought that came up, not sure if or how much that increases things. Or maybe I'm overlooking something.

**Comment by fregante** [comment]
That’s what the array-simple config does exactly: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/array-type.md

XO’s config already uses array-simple so if it still doesn’t work correctly it should be reported to TS-ESLint. It’s not something XO can fix anyway.
