### ISSUE TITLE
Disable @typescript-eslint/no-non-null-asserted-optional-chain in TS 3.9

### ISSUE THREAD

**Issue by fregante** [xojs/eslint-config-xo-typescript#26]
From: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/#breaking-changes

> Specifically, in previous versions, the code
> 
> ```ts
> foo?.bar!.baz
> ```
> was interpreted to be equivalent to the following JavaScript.
> ```ts
> (foo?.bar).baz
> ```
> In the above code the parentheses stop the “short-circuiting” behavior of optional chaining, so if foo is undefined, accessing baz will cause a runtime error.

`@typescript-eslint/no-non-null-asserted-optional-chain` made sense in that case but TS 3.9 will change the behavior to this:

> ```ts
> foo?.bar.baz
> ```
> which just evaluates to `undefined` when `foo` is undefined.

So `foo?.bar!.baz` becomes perfectly reasonable to catch an undefined `foo` but ignore an undefined `foo.bar`

**Comment by sindresorhus** [comment]
Can you open an issue on https://github.com/typescript-eslint/typescript-eslint? It seems like the whole rule is moot then.

**Comment by fregante** [comment]
Done

**Comment by sindresorhus** [comment]
Closing as the issues with this rule has been fixed.
