### ISSUE TITLE
Definition for rule typescript/generic-type-naming was not found 

### ISSUE THREAD

**Issue by iwata** [xojs/eslint-config-xo-typescript#3]
I upgrade this config to `0.3.0` and it shows `Definition for rule typescript/generic-type-naming was not found`.

I tested with these versions.

- typescript: `3.1.6`
- typescript-eslint-parser: `21.0.1`
- eslint-plugin-typescript: `0.12.0`

**Comment by sindresorhus** [comment]
https://github.com/xojs/eslint-config-xo-typescript/blob/fdda6f1a712f9ba2ea72f98449492087509d8d57/package.json#L54

**Comment by iwata** [comment]
Oh, I see.
But the version has this issue 😭 
https://github.com/bradzacher/eslint-plugin-typescript/issues/188
Thanks!
