### ISSUE TITLE
tsconfig 0.9 and dot-notation

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/eslint-config-xo-typescript#34]
[tsconfig 0.9.0](https://github.com/sindresorhus/tsconfig/releases/tag/v0.9.0) introduced `noPropertyAccessFromIndexSignature` which requires refactoring from `foo.bar` to `foo['bar']`. `xo` then errors on [`@typescript-eslint/dot-notation`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/dot-notation.md) as `foo['bar']` can be written as `foo.bar`.

The relevant tracking issue: https://github.com/typescript-eslint/typescript-eslint/issues/3104
(I already saw your thumbs up on the issue)

As a temporary fix xo might disable this rule (changing it only to warn would end up in `xo --fix` which "fixes" it which is annoying then).
Re enable when the mentioned issue is fixed.
The alternative is to wait with the tsconfig 0.9 upgrade. (While writing this issue I think this might be the easiest way to handle this)

**Comment by sindresorhus** [comment]
Finally fixed: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.24.0
