### ISSUE TITLE
add no-explicit-any

### ISSUE THREAD

**Issue by danny007in** [xojs/eslint-config-xo-typescript#36]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md

**Comment by EdJoPaTo** [comment]
https://github.com/xojs/eslint-config-xo-typescript/blob/72fbc202ceb2b2d10ccb7636b462fe52f45dad5a/index.js#L295-L304
