### ISSUE TITLE
Type Parameter name `TPublicMethod` must match one of the following formats: StrictPascalCase

### ISSUE THREAD

**Issue by fregante** [xojs/eslint-config-xo-typescript#41]
It seems that the config allows types named "TSomething":

https://github.com/xojs/eslint-config-xo-typescript/blob/7c1e7d23437d975f7031324ec12250985eb4ae7a/index.js#L331

but I'm getting this error:

```
  274:3   error    Type Parameter name `TMethod` must match one of the following formats: StrictPascalCase                                                      @typescript-eslint/naming-convention
  275:3   error    Type Parameter name `TPublicMethod` must match one of the following formats: StrictPascalCase                                                @typescript-eslint/naming-convention
  278:3   error    Type Parameter name `TType` must match one of the following formats: StrictPascalCase                                                        @typescript-eslint/naming-convention
  279:3   error    Type Parameter name `TMethod` must match one of the following formats: StrictPascalCase                                                      @typescript-eslint/naming-convention
  280:3   error    Type Parameter name `TPublicMethod` must match one of the following formats: StrictPascalCase                                                @typescript-eslint/naming-convention
```

See run https://github.com/pixiebrix/webext-messenger/actions/runs/1300974580 for https://github.com/pixiebrix/webext-messenger/pull/35.

**Comment by fregante** [comment]
If this is intentional, I was under the impression that TSomething is the convention to name a local parameter, like `Array<TSomething extends Something>`

**Comment by sindresorhus** [comment]
I intentionally don't allow `T`-prefixed type parameter names as I see it as an anti-pattern. Just use the pure name or `Type` suffix if it conflicts.

https://til.hashrocket.com/posts/cfnlyzxcrc-do-not-prefix-typescript-interface-names

**Comment by fregante** [comment]
The article is about `ISomething`, which is fine. `TSomething` seems used a lot and I don’t think enforcement is worth it.

**Comment by sindresorhus** [comment]
The same arguments apply though. You can see that the TS docs does not use the `T` prefix either: https://www.typescriptlang.org/docs/handbook/2/generics.html#working-with-generic-type-variables

**Comment by fregante** [comment]
I don’t think that page helps your argument since it contains 

- `Type extends Lengthwise`
- `A extends Animal`

as 2 of the 3 examples that use `extends` in generics. 😃 

The main issue is that `extends Foo` usually refers to a well-defined "global" type, and the `TFoo` refers to the local version of it. Which is really still a `Foo`, but scoped to the function. Other than calling it `LocalFoo` or `ScopedFoo`, I don't see many alternatives — and are those any better than the conventional `TFoo`? I'd argue they aren't

**Comment by sindresorhus** [comment]
Before:

```ts
function getMethod<
  TType extends keyof MessengerMethods,
  TMethod extends MessengerMethods[TType],
  TPublicMethod extends PublicMethod<TMethod>
>(
  type: TType,
  options: { isNotification: true }
): SetReturnType<TPublicMethod, void>;
```

After:

```ts
function getMethod<
  Type extends keyof MessengerMethods,
  Method extends MessengerMethods[Type],
  PublicMethodType extends PublicMethod<Method>
>(
  type: Type,
  options: { isNotification: true }
): SetReturnType<PublicMethodType, void>;
```

**Comment by fregante** [comment]
If you want to look at what Microsoft does, check their libs, they all use single-letters: 

- https://github.com/microsoft/TypeScript/tree/main/lib
- https://github.com/microsoft/vscode/blob/a4342f3addc29f405a5cb4aab359b0b98223411e/src/vs/vscode.d.ts#L2320

**Comment by fregante** [comment]
The first 2 are fine, so I'll try following it, but `PublicMethodType` isn't better than `TPublicMethod` — but maybe it's just a casualty/exception of the improved 2 other types.

**Comment by sindresorhus** [comment]
I generally use `T` or `Value` if there's only one generic type parameter, unless it's not immediately clear what `T` is, then I use a more descriptive name. If there are more than one, I always use descriptive names.

**Comment by EdJoPaTo** [comment]
Personal opinion: in most cases with a conflict the naming isnt descriptive enough for a casual human reader to understand their differences. So in most cases the improved names are also easier to understand afterwards.

If it is the special case of something TypeScript is able to differentiate between them and uses the "inner" specified one. But using a better name than just T as a prefix is also better here in my opinion.
