### ISSUE TITLE
@typescript-eslint/naming-convention: enumMember should not be in `strictCamelCase`

### ISSUE THREAD

**Issue by jonahsnider** [xojs/eslint-config-xo-typescript#43]
https://github.com/xojs/eslint-config-xo-typescript/blob/7c1e7d23437d975f7031324ec12250985eb4ae7a/index.js#L286

`enumMember`s should not be in `strictCamelCase`.

TypeScript documentation doesn't make a specific recommendation of `enum` member naming, although they exclusively use `StrictPascalCase` and `UPPER_CASE` (both of which are reasonable).

**Comment by sindresorhus** [comment]
It was an intentional choice. I'm aware the TS docs use pascal-case, but it honestly makes no sense to me. Enum cases are members, and all other kinds of members are camel-case.

I think the Swift style enum casing looks the best and makes the most sense:

```swift
enum CardSuit {
    case clubs
    case diamonds
    case hearts
    case spades
}
```

**Comment by sindresorhus** [comment]
> That seems like a weird decision to make, we aren't writing Swift, we're writing TypeScript.

TypeScript makes a ton of mistakes and weird choices by default.

> Node.js themselves use UPPER_CASE for enum values (ex. os.constants.signals).

Those are not enum values though. And Node.js is not a good example of well-done APIs.

> Also worth mentioning is that enum members are implicitly types as well as values:

This would be totally fine too:

```js
const value: Color.r = Color.r;
```

> Having this rule seems like a mistake and I think most other XO users will agree.

I think most people don't use TS enums as they're weirdly designed and also doesn't fit with JS. Most people use unions.

**Comment by sindresorhus** [comment]
That being said, I don't use TS enums, so I agree with just ignoring it in the rule: https://github.com/xojs/eslint-config-xo-typescript/releases/tag/v0.45.2
