### ISSUE TITLE
Allow PascalCase to React Component in `@typescript-eslint/naming-convention` rule

### ISSUE THREAD

**Issue by younho9** [xojs/eslint-config-xo-typescript#48]
Currently `@typescript-eslint/naming-convention` rule reports "react function component is not `strictCamelCase`."

How about add overrides for `.tsx` (react file extension) ?

Maybe can override it in the following way or copy all configuration for `@typescript-eslint/naming-convention`

```js
overrides: [
  {
    files: ['**/*.tsx'],
    rules: {
      // ...
      '@typescript-eslint/naming-convention': [
        'error',
        {
          selector: 'function',
          format: ['PascalCase', 'camelCase'],
        },
      ],
    },
  },
]
```

**Comment by fregante** [comment]
I don't know how common this is in react, but react-table also uses object properties to specify components, so they're in PascalCase

https://react-table.tanstack.com/docs/quick-start#define-columns

So I had to append this to the config:

```js
{
  selector: ["function", "objectLiteralProperty", "objectLiteralMethod"],
  format: ["PascalCase", "camelCase"]
}
```

**Comment by younho9** [comment]
I found variable name could be PascalCase when declare component as arrow function.

This is enforced in the [xo-react rule](https://github.com/xojs/eslint-config-xo-react/blob/main/index.js#L27-L33).

**Comment by sindresorhus** [comment]
PR welcome
