### ISSUE TITLE
Conflict with Prettier

### ISSUE THREAD

**Issue by felixfbecker** [xojs/eslint-config-xo-typescript#5]
```ts
const listener = (_event: ElectronEvent, arg: {emoji: string; dataUrl: string}): void => {
};
```
xo-typescript wants this to be formatted
```ts
dataUrl: string;}
```
but Prettier wants this to be formatted
```ts
dataUrl: string}
```

**Comment by sindresorhus** [comment]
Are you using the latest version? I think I already fixed this: https://github.com/xojs/eslint-config-xo-typescript/commit/dfb137f31c43f6c1ed6b7a43d93ebc900fe99d2a
