### ISSUE TITLE
Enable `@typescript-eslint/consistent-type-definitions` rule

### ISSUE THREAD

**Issue by jonahsnider** [xojs/eslint-config-xo-typescript#57]
It's been about 3 years since `@typescript-eslint/consistent-type-definitions` was added to this config as a disabled rule.

https://github.com/xojs/eslint-config-xo-typescript/blob/79d6708032b09ab76765eb369530a83df31daf85/index.js#L211-L215

Can we re-enable it?

The rule has an automated fixer which should make adoption easy.
I'm not sure there are any situations where you'd even need to manually make the change.

---

I'll also mention that it may be worth revisiting the decision to prefer `type` over `interface`. Historically [there were performance concerns from using `type` instead of `interface`](https://ncjamieson.com/prefer-interfaces/), but I'm not sure if those are still relevant now.

**Comment by sindresorhus** [comment]
Yeah, I'll enable it in the next XO version.

**Comment by fregante** [comment]
This rule broke everything for me, I don't see the appeal at all. `types` cannot be used for declaration merging so it shouldn't autofix code
