### ISSUE TITLE
Rule "no-extraneous-class" currently broken

### ISSUE THREAD

**Issue by sebald** [xojs/eslint-config-xo-typescript#6]
Just a heads up, the `no-extraneous-class` rule currently does not seem to work.
See https://github.com/typescript-eslint/typescript-eslint/issues/170

*Workaround:*

```
"rules": {
  "@typescript-eslint/no-extraneous-class": "off"
}
```

**Comment by sindresorhus** [comment]
Closing as this was fixed in https://github.com/typescript-eslint/typescript-eslint/pull/174.
