### ISSUE TITLE
should `@typescript-eslint/parser` be listed in peer dependencies?

### ISSUE THREAD

**Issue by aladdin-add** [xojs/eslint-config-xo-typescript#60]
a while ago, the xo style guide has been added to `@eslint/create-config`. In the [PR](https://github.com/eslint/create-config/pull/33) we tried to switch to use the package `eslint-config-xo-typescript` when users choose typescript + xo. 

the problem is: `@typescript-eslint/parser` was not listed in its peer dependencies.  Surely, it's not an issue for npm v7+ users - it's listed in `@typescript-eslint/eslint-plugin`'s peerdeps and will be auto installed. But it won't work for yarn/pnpm/... users.

related discussion: https://github.com/eslint/create-config/pull/33

**Comment by sindresorhus** [comment]
I feel that's an issue Yarn and PNPM needs to resolve.

But if anyone feels strongly and cares enough to contribute a fix, I will merge it.
