### ISSUE TITLE
Upgrade `@typescript-eslint/eslint-plugin` dependency to `5.45.0` minimum.

### ISSUE THREAD

**Issue by devunt** [xojs/eslint-config-xo-typescript#74]
Please upgrade peer dependency of `@typescript-eslint/eslint-plugin` to `5.45.0` minimum.

https://github.com/typescript-eslint/typescript-eslint/issues/6077 fixes an issue with `satisfies` keyword incorrectly interferes with `@typescript-eslint/consistent-type-imports` rule. We use `satisfies` keyword in our codebase heavily, but the peer dependency of `xo` makes it impossible to use `@typescript-eslint/consistent-type-imports` rule and forcing us to disable the rule.

**Comment by sindresorhus** [comment]
Done in: https://github.com/xojs/xo/releases/tag/v0.54.0
