### ISSUE TITLE
Override just part of rule

### ISSUE THREAD

**Issue by fabulousgk** [xojs/eslint-config-xo-typescript#86]
Specifically, I am trying to modify the @typescript-eslint/naming-convention rule.  I want to keep almost all of the rule as defined in xo, I only need to change one selector.  But, as soon as I put one selector in, all rules are overridden.

Is there any way to keep most the rules and just add to them without copying the entire thing from xo config?

**Comment by sindresorhus** [comment]
This would be a question for ESLint as it's not specific to this config.

But to answer your question, I think the new ESLint flat config will allow this as you could just modify the config object from this package before adding it to your config.
