### ISSUE TITLE
eslint v9 and typescript-eslint v8 support

### ISSUE THREAD

**Issue by spence-s** [xojs/eslint-config-xo-typescript#87]
as of https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.0.0 eslint-config-xo-typescript is not compatible with the rule changes,  lots of rules have changed or have been drop and I believe TSESL dropped a lot of rules and defers them to eslint or stylistic plugins.

**Comment by EdJoPaTo** [comment]
https://github.com/xojs/xo/issues/757
