### ISSUE TITLE
Configuration is invalid error

### ISSUE THREAD

**Issue by satyarohith** [xojs/eslint-config-xo-typescript#9]
I'm getting the below error:
```
Error: /home/s/c/github.com/sindresorhus/pageres/node_modules/eslint-config-xo-typescript/index.js:
        Configuration for rule "@typescript-eslint/no-empty-interface" is invalid:
        Value [{"allowSingleExtends":true}] should NOT have more than 0 items.
```
[`no-empty-interface`](https://github.com/xojs/eslint-config-xo-typescript/blob/master/index.js#L127)

**Comment by satyarohith** [comment]
Reinstalling node modules fixed this.

**Comment by provinceinnovation** [comment]
If anyone stumbles across this I had to clean reinstall node_modules using `npm ci`, then restart VSCode. Just restarting the extension host did not work.
