### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by joao-offerfit** [xojs/eslint-config-xo-typescript#90]
Hello guys,

I'm integrating XO under a Vue project using the XO CLI, and I'm having a hard time while trying to apply XO typescript rules under .vue files.

I already found a solution that require changes in the XO CLI ([issue](https://github.com/xojs/xo/issues/768))

Meanwhile, I am trying to extend `xo-typescript` into `.vue` files, so I can achieve the same result (even if it's redundant as XO have it already bundled)

I am consistently receiving the error: `Error [ERR_REQUIRE_ESM]: require() of ES Module`

I made a repo from scratch where it is possible to reproduce the issue. Could someone help me understand why this happens?

Repo: https://github.com/joao-offerfit/vue-xo-demo

**Comment by fregante** [comment]
I ran `npm run xo` on that project and I don't see the issue. Please include more info.

Either way, this is not a problem with this config.

**Comment by joao-offerfit** [comment]
Sorry,  I should have provided better directions.

Try running `npx xo --print-config=src/App.vue > output.txt`, it does not work while I have `xo-typescript` under my `extends` applied to `.vue` files.

(I also use `pnpm` instead of `npm` in this project but I don't think this changes anything)

**Comment by fregante** [comment]
Check out the readme on this repo. If you use XO, you can't use this config.

**Comment by joao-offerfit** [comment]
Makes sense! Thanks for clarifying!

**Comment by joao-offerfit** [comment]
You gave me an incredible idea... It works if I use v5 (which does not use flat config). Thank you so much for that!
